<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="jhet" failures="1" tests="5" name="Test" time="35.149" errors="0" timestamp="2024-06-04T23:53:34 IST">
  <testcase classname="tests.TwoTest" name="testTwo" time="0.02"/>
  <testcase classname="tests.ThreeTest" name="testThree" time="0.003"/>
  <testcase classname="tests.LogincTest" name="login" time="11.447">
    <failure type="java.lang.AssertionError" message="expected [Successfull] but found [Failure]">
      <![CDATA[java.lang.AssertionError: expected [Successfull] but found [Failure]
at tests.LogincTest.login(LogincTest.java:47)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="tests.LogincTest" name="login" time="11.162"/>
  <testcase classname="tests.FourTest" name="testFour" time="0.002"/>
</testsuite> <!-- Test -->
